
version: '3.8'


services:

  db:
    container_name: database
    image: postgres:12.0-alpine
    env_file: ./backend/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DEBUG: 0
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: core
      SQL_USER: user
      SQL_PASSWORD: password
      SQL_HOST: db
      SQL_PORT: 5432
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  static:
  media:

networks:
  app-network:
    driver: bridge
