apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: interview-app
type: Opaque
stringData:
  SQL_USER: "dbuser"
  SQL_PASSWORD: "password123"
  SQL_HOST: "interview-eks-postgres.ceh6y8q6kmi5.us-east-1.rds.amazonaws.com"
  SECRET_KEY: "django-insecure-secret-key-change-in-production"
