apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: interview-app
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000              
    targetPort: 8000        
    protocol: TCP
  selector:
    app: backend
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
